### ISSUE TITLE
Issue of sys.exit(main()) in fivetran-connector-sdk package files

### ISSUE THREAD

**Issue by lewisosborne** [fivetran/fivetran_connector_sdk#41]
I have installed version `fivetran_connector_sdk    0.10.7.1`

I am simply testing the "hello_world" example - i.e. as in the Docs [here](https://github.com/fivetran/fivetran_connector_sdk/blob/main/examples/quick_start_examples/hello/connector.py)

`fivetran debug` cmd works ✅ ( inc. warehouse.db is generated along with the 'hello' target table ✅ )

However, upon running a `fivetran deploy` command I encounter an error, which refers to fivetran-connector-sdk package files. How can I debug & pass this error?:

```
(fivetran-venv-3.11.8) monty.camelot on-fivetran % fivetran deploy --destination Warehouse_DevTestUAT --connection hello
WARNING: `requirements.txt` is not required as no additional Python libraries are required or all required libraries for your code are pre-installed.
Successful validation of requirements.txt
Traceback (most recent call last):
  File "/Users/monty.camelot/.pyenv/versions/fivetran-venv-3.11.8/bin/fivetran", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/monty.camelot/.pyenv/versions/fivetran-venv-3.11.8/lib/python3.11/site-packages/fivetran_connector_sdk/__init__.py", line 1392, in main
    connector_object.deploy(args.project_path, ft_deploy_key, ft_group, ft_connection, configuration)
  File "/Users/monty.camelot/.pyenv/versions/fivetran-venv-3.11.8/lib/python3.11/site-packages/fivetran_connector_sdk/__init__.py", line 630, in deploy
    connection_id, service = self.__get_connection_id(
                             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monty.camelot/.pyenv/versions/fivetran-venv-3.11.8/lib/python3.11/site-packages/fivetran_connector_sdk/__init__.py", line 728, in __get_connection_id
    return Optional[None, None]
           ~~~~~~~~^^^^^^^^^^^^
  File "/Users/monty.camelot/.pyenv/versions/3.11.8/lib/python3.11/typing.py", line 365, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/monty.camelot/.pyenv/versions/3.11.8/lib/python3.11/typing.py", line 488, in __getitem__
    return self._getitem(self, parameters)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monty.camelot/.pyenv/versions/3.11.8/lib/python3.11/typing.py", line 712, in Optional
    arg = _type_check(parameters, f"{self} requires a single type.")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/monty.camelot/.pyenv/versions/3.11.8/lib/python3.11/typing.py", line 197, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: typing.Optional requires a single type. Got (None, None).
```

**Comment by varundhall** [comment]
Hi @lewisosborne,

There was a bug in version 0.10.7.1 that is likely causing the issue you're encountering.
Could you please update to the [latest version](https://pypi.org/project/fivetran-connector-sdk/0.10.15.1/)?

You can do this by running:
```
pip install --upgrade fivetran_connector_sdk
```

Feel free to reach out if you run into any other problems! 😄
